### ISSUE TITLE
Firefox 53.0.2 (64 bit, Windows)  scrolls only <see Mouse Properties> pixels every notch (WheelEvent.deltaMode is not used) 

### ISSUE THREAD

**Issue by Darsstar** [vaadin/vaadin-core-elements#117]
How to reproduce: go to https://cdn.vaadin.com/vaadin-grid/2.0.0/demo/row-details.html and scroll.

Related: https://github.com/vaadin/framework/issues/6578, https://github.com/vaadin/framework/issues/6384

In my case it scrolls 3 pixels per notch:
![image](https://cloud.githubusercontent.com/assets/104949/25944547/ffc61062-3643-11e7-86ab-b4b1022d7c02.png)

**Comment by manolo** [comment]
@Darsstar this issue is specific of vaadin-grid, do you mind to open this issue in the vaadin-grid repository, so as we can track it correctly.

Additionally, I have been able to reproduce the problem. We can pickup the solution from the JSNI block in the framework : https://github.com/vaadin/framework/commit/f4069826

**Comment by manolo** [comment]
Moved to https://github.com/vaadin/vaadin-grid/issues/883
