### ISSUE TITLE
Add ZIP archive with all bundled elements to release downloads

### ISSUE THREAD

**Issue by ktiedt** [vaadin/vaadin-core-elements#24]
The release downloads do not contain vaadin-grid currently...

**Comment by jounik** [comment]
Right, good point. We haven’t really considered providing the ZIP package in GitHub also, we only offer that on https://vaadin.com/download 

But now that you mention it, we might want to change it so that we provide them primarily in GitHub and just link to them from vaadin.com

I actually thought no one really uses the ZIP packages anymore, but we checked our logs for vaadin.com and apparently someone is downloading it (not sure if those could be bots or something).

Do you guys need the ZIP package?

**Comment by jounik** [comment]
If we want to go the route that we provide the ZIP on GitHub primarily, and just link from vaadin.com to it, we could still automate the process of uploading the package: https://developer.github.com/v3/repos/releases/#upload-a-release-asset

The only thing I’m wondering is if we can get any statistics from the downloads on GitHub?

**Comment by ktiedt** [comment]
We were going to import the vaadin elements into our third party codebase, instead, we opt'd to just cherry pick the vaadin-grid for now (and will add other elements as needed). I really only opened this ticket because, it seemed like an oversight considering you *do* generate meaningful zips for the sub projects

**Comment by manolo** [comment]
Added manually to latest release. Not sure if this is something we can do every release since the process for a final user looks very easy:

```
mkdir tmp_dir
cd tmp_dir
bower install vaadin-core-elements
zip -r vaadin-core-elements-1.6.0.zip bower_components/vaadin-*
```

**Comment by jouni** [comment]
> Not sure if this is something we can do every release since the process for a final user looks very easy

Well, you need to install npm and bower, and have access to those repos. In some companies it might be an issue, and you can only download packages using your web browser.

**Comment by jouni** [comment]
Anyway, not a big priority, as we haven’t really heard any complaints about this.

**Comment by manolo** [comment]
Let's see how much downloads we have, and then we can automatise the process.

**Comment by jouni** [comment]
1.5.0 has been downloaded 175 times.
