### ISSUE TITLE
vaadin-combo-box not work in angular2

### ISSUE THREAD

**Issue by jlno** [vaadin/vaadin-core-elements#92]
vaadin-combo-box not work in angular2, following this doc: https://vaadin.com/elements/-/element/vaadin-combo-box

**Comment by striff** [comment]
Same here... after update I am not able to select any item available in my dropdown (vaadin-combo-box element) because the app crashes with the following  error in console:

> **ORIGINAL STACKTRACE:**
ErrorHandler.handleError	@	error_handler.js:59
next	@	application_ref.js:359
schedulerFn	@	async.js:93
SafeSubscriber.__tryOrUnsub	@	Subscriber.js:223
SafeSubscriber.next	@	Subscriber.js:172
Subscriber._next	@	Subscriber.js:125
Subscriber.next	@	Subscriber.js:89
Subject.next	@	Subject.js:55
EventEmitter.emit	@	async.js:79
NgZone.triggerError	@	ng_zone.js:331
onHandleError	@	ng_zone.js:292
ZoneDelegate.handleError	@	zone.js:246
Zone.runTask	@	zone.js:154
ZoneTask.invoke	@	zone.js:345
fire	@	polymer.html:1337
_notifyChange	@	polymer.html:1468
_notifyEffect	@	polymer.html:1647
_effectEffects	@	polymer.html:1501
_propertySetter	@	polymer.html:1485
setter	@	polymer.html:1564
_overlaySelectedItemChanged	@	vaadin-combo-box-behavior.html:583
handler	@	polymer.html:560
ZoneDelegate.invokeTask	@	zone.js:275
onInvokeTask	@	ng_zone.js:262
ZoneDelegate.invokeTask	@	zone.js:274
Zone.runTask	@	zone.js:151
ZoneTask.invoke	@	zone.js:345
fire	@	polymer.html:1337
_onTap	@	vaadin-combo-box-overlay.html:193
handler	@	polymer.html:560
decorated	@	polymer.html:4477
ZoneDelegate.invokeTask	@	zone.js:275
onInvokeTask	@	ng_zone.js:262
ZoneDelegate.invokeTask	@	zone.js:274
Zone.runTask	@	zone.js:151
ZoneTask.invoke	@	zone.js:345
fire	@	polymer.html:1337
fire	@	polymer.html:909
forward	@	polymer.html:1206
click	@	polymer.html:1191
handleNative	@	polymer.html:799
ZoneDelegate.invokeTask	@	zone.js:275
onInvokeTask	@	ng_zone.js:262
ZoneDelegate.invokeTask	@	zone.js:274
Zone.runTask	@	zone.js:151
ZoneTask.invoke	@	zone.js:345

> EXCEPTION: Error in ./AddFormComponent class AddFormComponent - inline template:2:2 caused by: Cannot find a differ supporting object 'Concert'  **<-- Where 'Concert' is my selected item from the vaadin-combo-box dropdown.**

I am using the following in **package.json** file:
"dependencies": {
    "@angular/common": "^2.4.5",
    "@angular/compiler": "^2.4.5",
    "@angular/compiler-cli": "^2.4.5",
    "@angular/core": "^2.4.5",
    "@angular/forms": "^2.4.5",
    "@angular/http": "^2.4.5",
    "@angular/platform-browser": "^2.4.5",
    "@angular/platform-browser-dynamic": "^2.4.5",
    "@angular/router": "^3.4.5",
    "@types/node": "^7.0.0",
    "@vaadin/angular2-polymer": "^1.0.0",
    "angularfire2": "^2.0.0-beta.7",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "tslint": "^4.4.2",
    "zone.js": "^0.7.6"
  }

and on **bower.json** I have the following:
"dependencies": {
    "iron-ajax": "PolymerElements/iron-ajax#^1.0.0",
    "iron-list": "polymerelements/iron-list#^1.0.0",
    "iron-form": "polymerelements/iron-form#^1.0.10",
    "paper-elements": "^1.0.7",
    "vaadin-combo-box": "^1.2.0",
    "vaadin-date-picker": "^1.2.0",
    "vaadin-icons": "^2.0.0",
    "vaadin-upload": "^1.1.1",
    "vaadin-split-layout": "^1.0.0"
  }

In the template I have the following: 
  <vaadin-combo-box label="Categorie" name="categorieAleasa" [(value)]="categorie" [formControl]="myForm.controls['categorieAleasa']" [items]="categorii"></vaadin-combo-box>

[items] is an array similar to docs example - ['a','b','c','d','e'];
In the component I am creating the form control like this:
this.myForm = this.fb.group({
         'categorieAleasa': this.fb.control('', Validators.required)
});
value is an empty string variable in the component.

So what am I doing wrong ? Please help.
Thank you

**Comment by jlno** [comment]
@striff use the version 1.1.4 of combobox.
